#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-rake-compiler-dock
Version  : 0.5.2
Release  : 5
URL      : https://rubygems.org/downloads/rake-compiler-dock-0.5.2.gem
Source0  : https://rubygems.org/downloads/rake-compiler-dock-0.5.2.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: rubygem-rake-compiler-dock-bin
BuildRequires : ruby
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-test-unit

%description
# rake-compiler-dock
**Easy to use and reliable cross compiler environment for building Windows binary gems.**

%package bin
Summary: bin components for the rubygem-rake-compiler-dock package.
Group: Binaries

%description bin
bin components for the rubygem-rake-compiler-dock package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n rake-compiler-dock-0.5.2
gem spec %{SOURCE0} -l --ruby > rubygem-rake-compiler-dock.gemspec

%build
export LANG=C
gem build rubygem-rake-compiler-dock.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
rake-compiler-dock-0.5.2.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/rake-compiler-dock-0.5.2
ruby -v -I.:lib:test test*/test_*.rb || :
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/rake-compiler-dock-0.5.2.gem
/usr/lib64/ruby/gems/2.3.0/gems/rake-compiler-dock-0.5.2/.gitignore
/usr/lib64/ruby/gems/2.3.0/gems/rake-compiler-dock-0.5.2/Dockerfile
/usr/lib64/ruby/gems/2.3.0/gems/rake-compiler-dock-0.5.2/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/rake-compiler-dock-0.5.2/History.md
/usr/lib64/ruby/gems/2.3.0/gems/rake-compiler-dock-0.5.2/LICENSE.txt
/usr/lib64/ruby/gems/2.3.0/gems/rake-compiler-dock-0.5.2/README.md
/usr/lib64/ruby/gems/2.3.0/gems/rake-compiler-dock-0.5.2/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/rake-compiler-dock-0.5.2/bin/rake-compiler-dock
/usr/lib64/ruby/gems/2.3.0/gems/rake-compiler-dock-0.5.2/build/patches/rake-compiler-0.9.5/compat-with-bundler.diff
/usr/lib64/ruby/gems/2.3.0/gems/rake-compiler-dock-0.5.2/build/patches/rake-compiler-0.9.5/without-exts.diff
/usr/lib64/ruby/gems/2.3.0/gems/rake-compiler-dock-0.5.2/build/patches/ruby-1.8.7-p374/nop.patch
/usr/lib64/ruby/gems/2.3.0/gems/rake-compiler-dock-0.5.2/build/patches/ruby-1.9.3/no_sendfile.patch
/usr/lib64/ruby/gems/2.3.0/gems/rake-compiler-dock-0.5.2/build/patches/ruby-1.9.3/nop.patch
/usr/lib64/ruby/gems/2.3.0/gems/rake-compiler-dock-0.5.2/build/patches/ruby-2.3.0/no_sendfile.patch
/usr/lib64/ruby/gems/2.3.0/gems/rake-compiler-dock-0.5.2/build/runas
/usr/lib64/ruby/gems/2.3.0/gems/rake-compiler-dock-0.5.2/build/sigfw.c
/usr/lib64/ruby/gems/2.3.0/gems/rake-compiler-dock-0.5.2/build/strip_wrapper
/usr/lib64/ruby/gems/2.3.0/gems/rake-compiler-dock-0.5.2/build/sudoers
/usr/lib64/ruby/gems/2.3.0/gems/rake-compiler-dock-0.5.2/lib/rake_compiler_dock.rb
/usr/lib64/ruby/gems/2.3.0/gems/rake-compiler-dock-0.5.2/lib/rake_compiler_dock/colors.rb
/usr/lib64/ruby/gems/2.3.0/gems/rake-compiler-dock-0.5.2/lib/rake_compiler_dock/docker_check.rb
/usr/lib64/ruby/gems/2.3.0/gems/rake-compiler-dock-0.5.2/lib/rake_compiler_dock/predefined_user_group.rb
/usr/lib64/ruby/gems/2.3.0/gems/rake-compiler-dock-0.5.2/lib/rake_compiler_dock/starter.rb
/usr/lib64/ruby/gems/2.3.0/gems/rake-compiler-dock-0.5.2/lib/rake_compiler_dock/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/rake-compiler-dock-0.5.2/rake-compiler-dock.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/rake-compiler-dock-0.5.2/test/test_environment_variables.rb
/usr/lib64/ruby/gems/2.3.0/gems/rake-compiler-dock-0.5.2/test/test_starter.rb
/usr/lib64/ruby/gems/2.3.0/specifications/rake-compiler-dock-0.5.2.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/rake-compiler-dock
